GET http://127.0.0.1:5000/api/authors

###

GET http://127.0.0.1:5000/api/authors/1

###

POST http://127.0.0.1:5000/api/authors HTTP/1.1
Content-Type: application/json

{
  "full_name": "test1",
  "email": "test1@test.test"
}

###

PUT http://127.0.0.1:5000/api/authors HTTP/1.1
Content-Type: application/json

{
  "id": 2,
  "full_name": "test2",
  "email": "test2@test.test"
}

###

DELETE http://127.0.0.1:5000/api/authors/3