GET http://127.0.0.1:5000/api/customers

###

GET http://127.0.0.1:5000/api/customers/1

###

POST http://127.0.0.1:5000/api/customers HTTP/1.1
Content-Type: application/json

{
  "full_name": "test1",
  "password": "qwerty"
}

###

PUT http://127.0.0.1:5000/api/customers HTTP/1.1
Content-Type: application/json

{
  "id": 10,
  "full_name": "test2",
  "password": "qwerty"
}

###

DELETE http://127.0.0.1:5000/api/customers/3